# Generated by Django 4.1.7 on 2023-03-02 11:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Phone')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('first_name_en', models.CharField(max_length=30, null=True, verbose_name='First name')),
                ('first_name_ru', models.CharField(max_length=30, null=True, verbose_name='First name')),
                ('first_name_uz', models.CharField(max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Lastname')),
                ('last_name_en', models.CharField(max_length=30, null=True, verbose_name='Lastname')),
                ('last_name_ru', models.CharField(max_length=30, null=True, verbose_name='Lastname')),
                ('last_name_uz', models.CharField(max_length=30, null=True, verbose_name='Lastname')),
                ('photo', models.ImageField(blank=True, default='user.png', null=True, upload_to='authors', verbose_name='Photo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField(verbose_name='About author')),
                ('about_en', ckeditor.fields.RichTextField(null=True, verbose_name='About author')),
                ('about_ru', ckeditor.fields.RichTextField(null=True, verbose_name='About author')),
                ('about_uz', ckeditor.fields.RichTextField(null=True, verbose_name='About author')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('telegram', models.CharField(blank=True, max_length=70, null=True, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=70, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=70, null=True, verbose_name='Facebook')),
                ('twiter', models.CharField(blank=True, max_length=70, null=True, verbose_name='Twiter')),
                ('youtube', models.CharField(blank=True, max_length=70, null=True, verbose_name='Youtube')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_subscribers', to='user.authors', verbose_name='Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subsicribe',
                'verbose_name_plural': 'Subsicribes',
            },
        ),
    ]
