# Generated by Django 4.1.7 on 2023-03-02 11:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Phone')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Text')),
                ('text_uz', models.TextField(null=True, verbose_name='Text')),
                ('telegram', models.CharField(blank=True, max_length=70, null=True, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=70, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=70, null=True, verbose_name='Facebook')),
                ('twiter', models.CharField(blank=True, max_length=70, null=True, verbose_name='Twiter')),
                ('youtube', models.CharField(blank=True, max_length=70, null=True, verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_uz', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
                ('answer_en', ckeditor.fields.RichTextField(null=True, verbose_name='Answer')),
                ('answer_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Answer')),
                ('answer_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='SubscribeForNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'SubscribeForNewsletter',
                'verbose_name_plural': 'SubscribeForNewsletters',
            },
        ),
    ]
