# Generated by Django 4.1.7 on 2023-03-02 11:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('title', models.CharField(max_length=255, verbose_name='About user')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='About user')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='About user')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='About user')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('text_en', ckeditor.fields.RichTextField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(upload_to='articles', verbose_name='Image')),
                ('min_to_read', models.IntegerField(default=0, verbose_name='Minute to read')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='category_images', verbose_name='Icon image')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Text')),
                ('text_uz', models.TextField(null=True, verbose_name='Text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article.articles', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
